---                                                                                                                                  #- name: Download Zookeeper                                                                                                          #  get_url:                                                                                                                          #    url: "https://downloads.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar>#    dest: "/tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
- name: Download Zookeeper
  get_url:
    url: "https://downloads.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar>#    dest: "/tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"

- name: Extract Zookeeper
  unarchive:
    src: "/tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: "/opt"
    remote_src: yes
#  become_user: hadoop

- name: Change ownership of Zookeeper directory
  file:
    path: "{{ zookeeper_install_dir }}"
    state: directory
    owner: hadoop
    group: hadoop
    recurse: yes

- name: Create Zookeeper symlink
  file:
    src: "/opt/apache-zookeeper-{{ zookeeper_version }}-bin"
    dest: "{{ zookeeper_install_dir }}"
    state: link
  become_user: hadoop

- name: Create Zookeeper data directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
#  become_user: hadoop

- name: Change ownership of Zookeeper data directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    owner: hadoop
    group: hadoop
    recurse: yes

- name: Create Zookeeper configuration file
  template:
    src: "zoo.cfg.j2"
    dest: "{{ zookeeper_install_dir }}/conf/zoo.cfg"
  become_user: hadoop

- name: Create myid file
  copy:
    content: "{{ zookeeper_myid }}"
    dest: "{{ zookeeper_data_dir }}/myid"
  become_user: hadoop

- name: Start Zookeeper
  shell: "{{ zookeeper_install_dir }}/bin/zkServer.sh start"
  become: yes
  become_user: hadoop