---
- name: Setup Hadoop Common Configuration
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - java
    - zookeeper
    - hadoop

- hosts: master
  vars_files:
    - vars.yml
  roles:
    - hadoop-master

- hosts:  secondary_master
  vars_files:
    - vars.yml
  roles:
    - hadoop-secondary-master

- hosts: datanodes
  vars_files:
    - vars.yml
  roles:
    - hadoop-datanode